# Generated by Django 5.2.4 on 2025-07-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_remove_telegramuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='registered_at',
            field=models.DateTimeField(null=True),
        ),
    ]
